---
apiVersion: v1
kind: Namespace
metadata:
  name: train-schedule

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: train-schedule-ingress
  namespace: train-schedule
  labels:
    type: dev-app
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: "PathPrefixStrip"
spec:
  rules:
    - host: trainapp.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: train-schedule-svc
                port:
                  number: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: train-schedule-svc
  namespace: train-schedule
spec:
  type: NodePort
  selector:
    app: train-schedule
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  namespace: train-schedule
  labels:
    app: train-schedule
    type: dev-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
        type: dev-app
    spec:
      containers:
        - name: train-schedule
          image: ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 500Mi